"""Train an LSTM model for daily salinity forecasting.

The script is designed for the merged dataset generated by
`prepare_lstm_dataset.py`. It avoids temporal leakage by fitting imputers and
scalers only on the training period and by building windows whose target date is
strictly after the input window.

Install dependencies in your ML environment before running:

    pip install torch pandas numpy

Example:

    python train_lstm.py \
      --data Data/processed/lstm_daily_multisource_2020_2023.csv \
      --output-dir models/lstm_daily \
      --lookback 30 \
      --horizon 1 \
      --epochs 120 \
      --batch-size 128
"""

from __future__ import annotations

import argparse
import json
import math
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd

try:
    import torch
    from torch import nn
    from torch.utils.data import DataLoader, Dataset
except ImportError as exc:  # pragma: no cover - helpful runtime message
    raise SystemExit(
        "Missing PyTorch. Install it in your ML environment with: pip install torch"
    ) from exc


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_DATA = REPO_ROOT / "Data/lstm_processed/processed/lstm_daily_multisource_2020_2023.csv"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "models/lstm/lstm_daily"


@dataclass
class TrainConfig:
    data: str
    output_dir: str
    lookback: int
    horizon: int
    train_end: str
    val_end: str
    target_col: str
    batch_size: int
    epochs: int
    patience: int
    lr: float
    weight_decay: float
    hidden_size: int
    num_layers: int
    dropout: float
    station_embedding_dim: int
    grad_clip: float
    seed: int
    feature_set: str
    loss: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--lookback", type=int, default=30)
    parser.add_argument("--horizon", type=int, default=1)
    parser.add_argument("--train-end", type=str, default="2021-12-31")
    parser.add_argument("--val-end", type=str, default="2022-12-31")
    parser.add_argument("--target-col", type=str, default="target_salinity_max")
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=120)
    parser.add_argument("--patience", type=int, default=18)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--hidden-size", type=int, default=128)
    parser.add_argument("--num-layers", type=int, default=2)
    parser.add_argument("--dropout", type=float, default=0.20)
    parser.add_argument("--station-embedding-dim", type=int, default=8)
    parser.add_argument("--grad-clip", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--feature-set",
        choices=["salinity", "weather", "multisource", "multisource_compact"],
        default="multisource_compact",
        help="Feature ablation used for reproducible model comparison.",
    )
    parser.add_argument("--loss", choices=["huber", "mse"], default="huber")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def select_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


class MedianStandardizer:
    """Train-only median imputer plus standard scaler for numeric features."""

    def __init__(self) -> None:
        self.feature_cols: list[str] = []
        self.median: pd.Series | None = None
        self.mean: pd.Series | None = None
        self.std: pd.Series | None = None

    def fit(self, df: pd.DataFrame, feature_cols: list[str]) -> None:
        self.feature_cols = feature_cols
        train_values = df[feature_cols].replace([np.inf, -np.inf], np.nan)
        self.median = train_values.median(numeric_only=True).fillna(0.0)
        filled = train_values.fillna(self.median)
        self.mean = filled.mean()
        self.std = filled.std().replace(0, 1.0).fillna(1.0)

    def transform(self, df: pd.DataFrame) -> np.ndarray:
        if self.median is None or self.mean is None or self.std is None:
            raise RuntimeError("Standardizer has not been fitted")
        values = df[self.feature_cols].replace([np.inf, -np.inf], np.nan)
        values = values.fillna(self.median)
        values = (values - self.mean) / self.std
        return values.to_numpy(dtype=np.float32)

    def to_json_dict(self) -> dict[str, dict[str, float] | list[str]]:
        if self.median is None or self.mean is None or self.std is None:
            raise RuntimeError("Standardizer has not been fitted")
        return {
            "feature_cols": self.feature_cols,
            "median": self.median.to_dict(),
            "mean": self.mean.to_dict(),
            "std": self.std.to_dict(),
        }


def load_dataset(path: Path, target_col: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["date"])
    required = {"station_id", "date", target_col, "salinity_input"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Dataset is missing required columns: {sorted(missing)}")
    df = df.sort_values(["station_id", "date"]).reset_index(drop=True)
    return df


def choose_feature_columns(
    df: pd.DataFrame, target_col: str, feature_set: str
) -> list[str]:
    blocked = {
        "station_id",
        "date",
        "source_type",
        "source_dataset",
        "era5_imputed_from_station",
        "salinity_max",
        "salinity_min",
        target_col,
        # Raw calendar components are replaced by cyclic day-of-year features.
        "year",
        "month",
        "day",
        "day_of_year",
        "station_idx",
        "era5_buffer_m",
    }
    numeric = df.select_dtypes(include=[np.number]).columns.tolist()
    candidates = [c for c in numeric if c not in blocked]

    core = {
        "lat", "lon", "salinity_input", "salinity_input_imputed",
        "days_since_salinity_observed", "salinity_observed", "salinity_qc_invalid",
        "day_of_year_sin", "day_of_year_cos",
    }
    weather = {
        c for c in candidates
        if c in core or not c.startswith("s2_")
    }
    if feature_set == "salinity":
        allowed = core
    elif feature_set == "weather":
        allowed = weather
    elif feature_set == "multisource_compact":
        # Monthly S2 means carry the signal; per-band pixel counts and standard
        # deviations are highly redundant and greatly enlarge this small model.
        allowed = weather | {
            c for c in candidates
            if c.startswith("s2_")
            and (c.endswith("_mean") or c in {"s2_s2_valid_image_count", "s2_month_available"})
        }
    else:
        allowed = set(candidates)
    feature_cols = [c for c in candidates if c in allowed]

    preferred_first = [
        "lat",
        "lon",
        "salinity_input",
        "salinity_input_imputed",
        "days_since_salinity_observed",
        "salinity_observed",
        "day_of_year_sin",
        "day_of_year_cos",
    ]
    ordered = [c for c in preferred_first if c in feature_cols]
    ordered.extend(c for c in feature_cols if c not in ordered)
    return ordered


def add_station_index(df: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, int]]:
    stations = sorted(df["station_id"].unique())
    mapping = {station_id: i for i, station_id in enumerate(stations)}
    out = df.copy()
    out["station_idx"] = out["station_id"].map(mapping).astype("int64")
    return out, mapping


def build_windows(
    df: pd.DataFrame,
    features: np.ndarray,
    target_col: str,
    lookback: int,
    horizon: int,
    split_name: str,
    train_end: pd.Timestamp,
    val_end: pd.Timestamp,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, pd.DataFrame]:
    x_list: list[np.ndarray] = []
    y_list: list[float] = []
    station_list: list[int] = []
    meta_rows: list[dict[str, object]] = []

    feature_df = df[["station_id", "station_idx", "date", target_col]].copy()
    for station_id, group in feature_df.groupby("station_id", sort=False):
        indices = group.index.to_numpy()
        dates = group["date"].to_numpy()
        targets = group[target_col].to_numpy(dtype=np.float32)
        station_idx = int(group["station_idx"].iloc[0])

        for end_pos in range(lookback - 1, len(group) - horizon):
            target_pos = end_pos + horizon
            target_date = pd.Timestamp(dates[target_pos])

            if split_name == "train" and target_date > train_end:
                continue
            if split_name == "val" and not (train_end < target_date <= val_end):
                continue
            if split_name == "test" and target_date <= val_end:
                continue
            if np.isnan(targets[target_pos]):
                continue

            window_indices = indices[end_pos - lookback + 1 : end_pos + 1]
            x_list.append(features[window_indices])
            y_list.append(float(targets[target_pos]))
            station_list.append(station_idx)
            meta_rows.append(
                {
                    "station_id": station_id,
                    "target_date": target_date.date().isoformat(),
                    "target": float(targets[target_pos]),
                    "input_start": pd.Timestamp(dates[end_pos - lookback + 1]).date().isoformat(),
                    "input_end": pd.Timestamp(dates[end_pos]).date().isoformat(),
                    "split": split_name,
                }
            )

    if not x_list:
        raise ValueError(f"No samples created for split '{split_name}'")

    x = np.stack(x_list).astype(np.float32)
    y = np.array(y_list, dtype=np.float32).reshape(-1, 1)
    station = np.array(station_list, dtype=np.int64)
    meta = pd.DataFrame(meta_rows)
    return x, y, station, meta


class SalinityWindowDataset(Dataset):
    def __init__(self, x: np.ndarray, y: np.ndarray, station_idx: np.ndarray) -> None:
        self.x = torch.from_numpy(x)
        self.y = torch.from_numpy(y)
        self.station_idx = torch.from_numpy(station_idx)

    def __len__(self) -> int:
        return len(self.y)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        return self.x[idx], self.station_idx[idx], self.y[idx]


class LSTMRegressor(nn.Module):
    def __init__(
        self,
        n_features: int,
        n_stations: int,
        station_embedding_dim: int,
        hidden_size: int,
        num_layers: int,
        dropout: float,
    ) -> None:
        super().__init__()
        self.station_embedding = nn.Embedding(n_stations, station_embedding_dim)
        self.lstm = nn.LSTM(
            input_size=n_features + station_embedding_dim,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=dropout if num_layers > 1 else 0.0,
            batch_first=True,
        )
        self.head = nn.Sequential(
            nn.LayerNorm(hidden_size),
            nn.Linear(hidden_size, hidden_size // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size // 2, 1),
        )

    def forward(self, x: torch.Tensor, station_idx: torch.Tensor) -> torch.Tensor:
        emb = self.station_embedding(station_idx)
        emb_seq = emb.unsqueeze(1).expand(-1, x.shape[1], -1)
        x = torch.cat([x, emb_seq], dim=-1)
        out, _ = self.lstm(x)
        return self.head(out[:, -1, :])


def rmse(pred: np.ndarray, target: np.ndarray) -> float:
    return float(np.sqrt(np.mean((pred - target) ** 2)))


def mae(pred: np.ndarray, target: np.ndarray) -> float:
    return float(np.mean(np.abs(pred - target)))


def r2_score(pred: np.ndarray, target: np.ndarray) -> float:
    ss_res = float(np.sum((target - pred) ** 2))
    ss_tot = float(np.sum((target - target.mean()) ** 2))
    return 1.0 - ss_res / ss_tot if ss_tot else float("nan")


def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    target_mean: float,
    target_std: float,
) -> tuple[dict[str, float], np.ndarray, np.ndarray]:
    model.eval()
    preds_scaled: list[np.ndarray] = []
    targets_scaled: list[np.ndarray] = []
    with torch.no_grad():
        for x, station_idx, y in loader:
            x = x.to(device)
            station_idx = station_idx.to(device)
            pred = model(x, station_idx).cpu().numpy()
            preds_scaled.append(pred)
            targets_scaled.append(y.numpy())
    pred_scaled = np.vstack(preds_scaled)
    target_scaled = np.vstack(targets_scaled)
    pred = pred_scaled * target_std + target_mean
    target = target_scaled * target_std + target_mean
    metrics = {
        "rmse": rmse(pred, target),
        "mae": mae(pred, target),
        "r2": r2_score(pred, target),
    }
    return metrics, pred.reshape(-1), target.reshape(-1)


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: torch.device,
    grad_clip: float,
) -> float:
    model.train()
    losses = []
    for x, station_idx, y in loader:
        x = x.to(device)
        station_idx = station_idx.to(device)
        y = y.to(device)
        optimizer.zero_grad(set_to_none=True)
        pred = model(x, station_idx)
        loss = criterion(pred, y)
        loss.backward()
        if grad_clip > 0:
            nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
        optimizer.step()
        losses.append(float(loss.item()))
    return float(np.mean(losses))


def scale_targets(
    y_train: np.ndarray,
    y_val: np.ndarray,
    y_test: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, float]:
    mean = float(y_train.mean())
    std = float(y_train.std())
    if std == 0 or math.isnan(std):
        std = 1.0
    return (y_train - mean) / std, (y_val - mean) / std, (y_test - mean) / std, mean, std


def save_predictions(path: Path, meta: pd.DataFrame, pred: np.ndarray, target: np.ndarray) -> None:
    out = meta.copy()
    out["y_true"] = target
    out["y_pred"] = pred
    out["error"] = out["y_pred"] - out["y_true"]
    out["abs_error"] = out["error"].abs()
    out.to_csv(path, index=False)


def main() -> None:
    args = parse_args()
    set_seed(args.seed)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    device = select_device()

    config = TrainConfig(
        data=str(args.data),
        output_dir=str(args.output_dir),
        lookback=args.lookback,
        horizon=args.horizon,
        train_end=args.train_end,
        val_end=args.val_end,
        target_col=args.target_col,
        batch_size=args.batch_size,
        epochs=args.epochs,
        patience=args.patience,
        lr=args.lr,
        weight_decay=args.weight_decay,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
        station_embedding_dim=args.station_embedding_dim,
        grad_clip=args.grad_clip,
        seed=args.seed,
        feature_set=args.feature_set,
        loss=args.loss,
    )
    (args.output_dir / "config.json").write_text(
        json.dumps(asdict(config), indent=2), encoding="utf-8"
    )

    df = load_dataset(args.data, args.target_col)
    df, station_mapping = add_station_index(df)
    feature_cols = choose_feature_columns(df, args.target_col, args.feature_set)
    started_at = time.time()

    train_end = pd.Timestamp(args.train_end)
    val_end = pd.Timestamp(args.val_end)
    scaler = MedianStandardizer()
    scaler.fit(df[df["date"].le(train_end)], feature_cols)
    features = scaler.transform(df)

    x_train, y_train, s_train, train_meta = build_windows(
        df, features, args.target_col, args.lookback, args.horizon, "train", train_end, val_end
    )
    x_val, y_val, s_val, val_meta = build_windows(
        df, features, args.target_col, args.lookback, args.horizon, "val", train_end, val_end
    )
    x_test, y_test, s_test, test_meta = build_windows(
        df, features, args.target_col, args.lookback, args.horizon, "test", train_end, val_end
    )

    y_train_s, y_val_s, y_test_s, target_mean, target_std = scale_targets(y_train, y_val, y_test)

    train_loader = DataLoader(
        SalinityWindowDataset(x_train, y_train_s, s_train),
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=False,
    )
    val_loader = DataLoader(
        SalinityWindowDataset(x_val, y_val_s, s_val),
        batch_size=args.batch_size,
        shuffle=False,
    )
    test_loader = DataLoader(
        SalinityWindowDataset(x_test, y_test_s, s_test),
        batch_size=args.batch_size,
        shuffle=False,
    )

    model = LSTMRegressor(
        n_features=len(feature_cols),
        n_stations=len(station_mapping),
        station_embedding_dim=args.station_embedding_dim,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
    ).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=max(3, args.patience // 4)
    )
    criterion = nn.MSELoss() if args.loss == "mse" else nn.HuberLoss(delta=1.0)

    metadata = {
        "feature_cols": feature_cols,
        "station_mapping": station_mapping,
        "target_mean": target_mean,
        "target_std": target_std,
        "scaler": scaler.to_json_dict(),
        "sample_counts": {
            "train": len(train_meta),
            "val": len(val_meta),
            "test": len(test_meta),
        },
        "device": str(device),
        "feature_set": args.feature_set,
    }
    (args.output_dir / "training_metadata.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )
    train_meta.to_csv(args.output_dir / "train_samples.csv", index=False)
    val_meta.to_csv(args.output_dir / "val_samples.csv", index=False)
    test_meta.to_csv(args.output_dir / "test_samples.csv", index=False)

    best_val_rmse = float("inf")
    best_epoch = -1
    history: list[dict[str, float | int]] = []

    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(
            model, train_loader, optimizer, criterion, device, args.grad_clip
        )
        val_metrics, _, _ = evaluate(model, val_loader, device, target_mean, target_std)
        scheduler.step(val_metrics["rmse"])

        row = {"epoch": epoch, "train_loss": train_loss, **{f"val_{k}": v for k, v in val_metrics.items()}}
        history.append(row)
        print(
            f"epoch={epoch:03d} train_loss={train_loss:.5f} "
            f"val_rmse={val_metrics['rmse']:.4f} val_mae={val_metrics['mae']:.4f} "
            f"val_r2={val_metrics['r2']:.4f}"
        )

        if val_metrics["rmse"] < best_val_rmse:
            best_val_rmse = val_metrics["rmse"]
            best_epoch = epoch
            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "config": asdict(config),
                    "metadata": metadata,
                    "best_epoch": best_epoch,
                    "best_val_rmse": best_val_rmse,
                },
                args.output_dir / "best_model.pt",
            )

        if epoch - best_epoch >= args.patience:
            print(f"Early stopping at epoch {epoch}; best epoch was {best_epoch}.")
            break

    pd.DataFrame(history).to_csv(args.output_dir / "training_history.csv", index=False)

    checkpoint = torch.load(args.output_dir / "best_model.pt", map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    val_metrics, val_pred, val_true = evaluate(model, val_loader, device, target_mean, target_std)
    test_metrics, test_pred, test_true = evaluate(model, test_loader, device, target_mean, target_std)

    save_predictions(args.output_dir / "val_predictions.csv", val_meta, val_pred, val_true)
    save_predictions(args.output_dir / "test_predictions.csv", test_meta, test_pred, test_true)

    metrics = {
        "best_epoch": best_epoch,
        "best_val_rmse": best_val_rmse,
        "val": val_metrics,
        "test": test_metrics,
        "elapsed_seconds": time.time() - started_at,
        "n_features": len(feature_cols),
    }
    (args.output_dir / "metrics.json").write_text(
        json.dumps(metrics, indent=2), encoding="utf-8"
    )
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
